### ISSUE TITLE
App doesn't work with dotted paths in INSTALLED_APPS

### ISSUE THREAD

**Issue by Tyrdall** [Fantomas42/django-app-namespace-template-loader#10]
Applications in Django>=1.7 can be added to the ``INSTALLED APPS`` by using the dotted path to their ``AppConfig``, e.g. 'app_name.apps.AppConfig'. 

This leads to an import error right here: https://github.com/Fantomas42/django-app-namespace-template-loader/blob/develop/app_namespace/loader.py#L55

Any ideas?

**Comment by Fantomas42** [comment]
Hello,

yes I have an idea.

This possibility was not expected when I was developing the module.

I need to make a fix.

**Comment by Tyrdall** [comment]
Thanks :)

**Comment by Fantomas42** [comment]
Version 0.3.1 will be released on Pypi with this feature.
