### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by EliotBerriot** [Fantomas42/django-app-namespace-template-loader#11]
On Django 1.9, it seems `django.template.base.TemplateDoesNotExist` as been removed, which cause template rendering to fail with the following stack trace : 

    """Template loader for app-namespace"""
       import os
       import sys
       from importlib import import_module
       from collections import OrderedDict
       
       import six
       
       from django.conf import settings
       from django.utils._os import safe_join
       from django.utils.functional import cached_property
    >   from django.template.base import TemplateDoesNotExist
    E   ImportError: cannot import name 'TemplateDoesNotExist'

    .tox/py34/lib/python3.4/site-packages/app_namespace/loader.py:12: ImportError

I'll make a pull request to solve this.

**Comment by Fantomas42** [comment]
Hello, thanks for your contribution,

but support for Django 1.9, is a little bit more complicated.
I'm currently working a branch to support it.

https://github.com/Fantomas42/django-app-namespace-template-loader/compare/feature/django-1.9

Please use this branch if possible.

**Comment by Fantomas42** [comment]
Hello, thanks for your contribution,

but support for Django 1.9, is a little bit more complicated.
I'm currently working a branch to support it.

https://github.com/Fantomas42/django-app-namespace-template-loader/compare/feature/django-1.9

Please use this branch if possible.

**Comment by headcrabz** [comment]
Hi Fantomas42 , is the dev  for django 1.9+ complete  ?

**Comment by patroqueeet** [comment]
I'd be glad about a stable release too

**Comment by Fantomas42** [comment]
Hello, sorry for the late release,

but the v0.4 compatible with Django 1.8 and 1.9 is now released on Pypi.

**Comment by tbodine88** [comment]
# Note that the missing code is simply:

'class TemplateDoesNotExist(Exception):
 &nbsp;&nbsp;   pass`
