### ISSUE TITLE
Doesn't work expectantly when use {% extends %} template tag.

### ISSUE THREAD

**Issue by ghost** [Fantomas42/django-app-namespace-template-loader#18]
I write these to code to cover the default tempate:

```
{% extends "zinnia_bootstrap:zinnia/skeleton.html" %}
{% load staticfiles %}
{% block link %}
<link rel="stylesheet" href="{% static "test.css" %}" />
{% endblock%}
```

but things doesn't work, <link rel="stylesheet" href="{% static "test.css" %}" /> doesn't populate on the link block. Nothing happened.

**Comment by Fantomas42** [comment]
Are you sure that the template is called ?

**Comment by ghost** [comment]
I think it is.If I delete above codes then refresh the page,it be a blank page.Or I put some characters on it,the page will show them.

**Comment by Fantomas42** [comment]
Which version of Django do you use ?

**Comment by ghost** [comment]
I use django 1.9.6 and latest zinnia version.
Does I describe the issue clearly? What I want to do is add a css style sheet to zinnia_bootstrap/zinnia/skeleton.html (I install the bootstrap theme). Now the problem is cannot populate block link.
Here is my settings for template loader:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'zinnia.context_processors.version',  # Optional
            ],
            'loaders': [
                'app_namespace.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]
```

**Comment by Fantomas42** [comment]
Okay, I will try to reproduce your issue ASAP.

**Comment by zmrenwu** [comment]
Thanks a lot! In addition,my template directory structure is `templates/zinnia/skeleton.html`,

**Comment by zmrenwu** [comment]
Thanks a lot! In addition,my template directory structure is `templates/zinnia/skeleton.html`,

**Comment by ghost** [comment]
Thanks a lot! In addition,my template directory structure is `templates/zinnia/skeleton.html`,

**Comment by Fantomas42** [comment]
Hello,

sorry for the late reply.

This does not work because later in the original zinnia/base.html the block *link* in populated without a block.super, so your modification is overridden.

So to accomplish what you what, you have to create a template named zinnia/base.html with this content:

```
{% extends "zinnia_bootstrap:zinnia/base.html" %}
{% load staticfiles %}

{% block link %}
<link rel="stylesheet" href="{% static "test.css" %}" />
{{ block.super }}
{% endblock%}
```

Regards
