### ISSUE TITLE
TEMPLATE_LOADERS deprecated in 1.8

### ISSUE THREAD

**Issue by datakid** [Fantomas42/django-app-namespace-template-loader#4]
https://docs.djangoproject.com/en/1.8/ref/settings/#template-loaders

"Set the 'loaders' option in the OPTIONS of a DjangoTemplates backend instead."

**Comment by datakid** [comment]
I'm not a good enough programmer to know how to update this app properly, especially being able to provide support for Django 1.7 but in the mean time:

app_namespace/loader.py needs to have two lines fixed:

**Comment by datakid** [comment]
Actually [this documentation](https://docs.djangoproject.com/en/1.8/releases/1.8/#django-template-loader-baseloader) is insufficient as in [Django 1.7](https://github.com/django/django/blob/1.7.7/django/template/loader.py):
```
class BaseLoader(base.Loader):
    _accepts_engine_in_init = False

    def __init__(self, *args, **kwargs):
```

Whereas the replacement from [Django 1.8](https://github.com/django/django/blob/1.8/django/template/loaders/base.py):
```
class Loader(object):
    is_usable = False
    # Only used to raise a deprecation warning. Remove in Django 2.0.
    _accepts_engine_in_init = True

    def __init__(self, engine):
        self.engine = engine
```

Discovered via the error:
```
Exception Type: 	TypeError
Exception Value: 	__init__() takes exactly 2 arguments (3 given)
```

**Comment by datakid** [comment]
Ok, I've worked this one out and it works.

First, we need to adjust my first change, given the name clash:
```
from django.template.loaders.base import Loader as L
```
Then we need to change the call to init, because it has a new shape:
```class Loader(L):
    """
    App namespace loader for allowing you to both extend and override
    a template provided by an app at the same time.
    """
    is_usable = True

    def __init__(self, engine):
        super(Loader, self).__init__(engine)
        self._already_used = []
```
FWIW, I've also updated jquery.js to 2.1.3 and bootstrap to 3.3.4 and it still works fine.

**Comment by Fantomas42** [comment]
@datakid I have just made a new release (v0.3) enabling the support for Django 1.8.

Note: support for Python 2.6 has been dropped.

Thanks for your participation.

**Comment by datakid** [comment]
No problems - thanks for your code!
