### ISSUE TITLE
'Loader' object has no attribute 'make_origin'

### ISSUE THREAD

**Issue by m0r13** [Fantomas42/django-app-namespace-template-loader#7]
After I had to upgrade my django version to 1.8.3, I ran into this issue with zinnia: http://dpaste.com/0DPVTA5

I opened this issue here because I figured this is a problem of the ``Loader`` class of this project, and not a problem of zinnia. I tried to update all the dependencies of zinnia and django-app-namespace-template-loader with pip to the newest version, but the problem persisted.

This looks like a newer version of django expects something differently of that template loader class. I'm not really into those django internals, can you have a look at this?

**Comment by Fantomas42** [comment]
Hello,

unfortunately your paste, is not available anymore...

I have made some tests with Django 1.8.4 and everything works fine.

I close the issue, until more informations.

Regards
