### ISSUE TITLE
I think it's a  bug 

### ISSUE THREAD

**Issue by time-river** [Fantomas42/django-app-namespace-template-loader#9]
I installed django-blog-zinnia. in the Djang Web project folder.
```
$tree -L 1
├── app_namespace
├── blog
├── db.sqlite3
├── manage.py
├── __pycache__
├── six.py
├── zinnia
├── zinnia_bootstrap
```
 then `$python3 manage.py runserver`
open localhost:8000/weblog, there is  this infomation
```
AttributeError at /weblog/
'module' object has no attribute '__file__'
Request Method:	GET
Request URL:	http://localhost:8000/weblog/
Django Version:	1.8.4
Exception Type:	AttributeError
Exception Value:	
'module' object has no attribute '__file__'
Exception Location:	/tmp/zinnia/blog/app_namespace/loader.py in app_templates_dirs, line 59
Python Executable:	/usr/bin/python3
Python Version:	3.4.3
Python Path:	
['/tmp/zinnia/blog',
 '/usr/local/lib/python3.4/dist-packages/Pillow-2.9.0-py3.4-linux-x86_64.egg',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']
Server time:	Wed, 21 Oct 2015 16:11:46 +0000
```
But I installed django-blog-zinnia. in `/usr/local/lib/python3/dist-packages/`,
then I test it, it is  normal.
Could you fix it?

**Comment by Fantomas42** [comment]
Hello,

I don't think that it's an issue related app_namespace, but to your configuration.

What do you have in your INSTALLED_APPS, because the issue is coming from an invalid module listed in this setting.

As usual without a way to reproduce the issue, I can't fix the issue.

Regards

**Comment by time-river** [comment]
Glad to hear from your Re.
I want to make Django install in docker in order to conveniently migrate, zinnia as Django's APP and I hope to customize it's model and view in the future(now，I'm a newer in Django), so installing zinnia and it's dependence behind Django project folder is a good choice.
I try to installing those(zinnia, six.py, bootstrap-theme, djang-app-namespace-template, and so on) behind Django projects folder. But I enter the URL(localhost:8000/weblog), it's have that's wrong information （using bootstrap theme）after running test server. However, moving djang-app-namespace-template-loader to /usr/local/lib/python3.4/dist-packags/ （or pip3 install djang-app-namespace-template-loader），it's normal that opening URL localhost:8000.

Could you understand what I meaning?
(My English is not good， I'm sorry, certain statements that may be hard for you to understand. If you had anything not understanding，I will try my best toexplain.）

-------- 原始邮件 --------
主题：Re: [django-app-namespace-template-loader] I think it's a bug (#9)
发件人：Julien Fache
收件人：Fantomas42/django-app-namespace-template-loader
抄送：time-river

Hello,

I don't think that it's an issue related app_namespace, but to your configuration.

What do you have in your INSTALLED_APPS, because the issue is coming from an invalid module listed in this setting.

As usual without a way to reproduce the issue, I can't fix the issue.

Regards

---

**Comment by Fantomas42** [comment]
I repeat :

> What do you have in your INSTALLED_APPS, because the issue is coming from an invalid module listed in this setting.

Regards
